// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TestTecnico.Migrations
{
    [DbContext(typeof(MeasuresContext))]
    [Migration("20240925212346_AddTable")]
    partial class AddTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Measure", b =>
                {
                    b.Property<int>("MeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasureId"));

                    b.Property<float>("Parameter1")
                        .HasColumnType("real");

                    b.Property<float>("Parameter2")
                        .HasColumnType("real");

                    b.Property<float>("Parameter3")
                        .HasColumnType("real");

                    b.Property<float>("Parameter4")
                        .HasColumnType("real");

                    b.HasKey("MeasureId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Threshold", b =>
                {
                    b.Property<int>("ThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThresholdId"));

                    b.Property<int>("Threshold1")
                        .HasColumnType("int");

                    b.Property<int>("Threshold2")
                        .HasColumnType("int");

                    b.Property<int>("Threshold3")
                        .HasColumnType("int");

                    b.Property<int>("Threshold4")
                        .HasColumnType("int");

                    b.HasKey("ThresholdId");

                    b.ToTable("Thresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
